version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    container_name: matcha_nginx

  backend_dev:
    container_name: matcha_backend_dev
    build: ./backend/
    environment:
      - VIRTUAL_HOST=si.matcha.local
    volumes : 
      - ./backend/:/usr/src/app:rw
    ports:
      - "3000:3000"
    command: "nodemon ./bin/www --inspect --legacy-watch"
    links:
      - "mysql:matcha_phpmyadmin"
  
  mysql:
    image: mysql:5.7
    env_file:
      - .env
    volumes:
      - ./.docker/data/mysql/:/var/lib/mysql
      - ./.docker/logs/mysql/:/var/log/mysql
    ports:
      - "3307:3306"
    container_name: matcha_mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      -  8080:80
    env_file:
      - .env
    environment:
      PMA_HOST: mysql
      VIRTUAL_HOST: phpmyadmin.matcha.local  
    container_name: matcha_phpmyadmin


  frontend_dev:
    container_name: natcha_app
    build: frontend/
    environment:
      - VIRTUAL_HOST=app.matcha.local
    volumes : 
      - ./frontend/:/usr/src/app:rw
    restart: always
    ports:
      - 8083:5000
    command: "npm start"